export { getTechCrunchNews } from "./techcrunch.js"
export { getBBCNews } from "./bbc.js"
export { getHackerNews } from "./hackernews.js"
export { getRedditNews } from "./reddit.js"
export { getCNNNews } from "./cnn.js"
export { getReutersNews } from "./reuters.js"
export { getGuardianNews } from "./guardian.js"
